import React from 'react'

import {ProgressBar} from 'react_pageread_progress_bar'

const App = () => {
  return <>
    <ProgressBar position="fixed" barColor={"#4E4C67"} containerColor={"white"}/>
    <h1>Article.</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis maximus dolor, quis ultricies eros. Nullam quam urna, volutpat sit amet felis eu, scelerisque efficitur diam. Duis dictum, tortor vitae sollicitudin mattis, ex nulla consectetur ligula, sit amet facilisis nisi ante sit amet massa. Donec scelerisque sed ex in faucibus. Aenean et purus vel justo pharetra fermentum. Maecenas rutrum venenatis mi at pellentesque. Vestibulum bibendum sodales est at convallis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed ante mi, pharetra id mollis eget, posuere in lectus. Nullam augue nibh, scelerisque ac odio tempus, pharetra ultrices leo. Etiam vestibulum nunc vehicula elit porta euismod. Fusce iaculis quam est, ut accumsan quam euismod ac. Phasellus porttitor at arcu vitae scelerisque. Sed vehicula velit at odio rhoncus faucibus. Morbi euismod vel dolor et blandit.

Ut ut sem a felis dictum aliquam. Curabitur elementum, mi eu tempor suscipit, nunc sapien accumsan enim, at porttitor ligula magna ut turpis. Morbi risus massa, gravida sed sapien eu, consequat vestibulum ante. Etiam nec iaculis enim, a aliquet sem. Praesent non vulputate eros. Aenean luctus sed quam eget blandit. Maecenas ut lobortis sapien.

Proin facilisis erat in aliquam maximus. Ut a accumsan risus, vel malesuada est. Mauris tempor arcu sapien, ut sodales enim venenatis id. Nunc varius diam a imperdiet placerat. Nulla et turpis diam. Vivamus sed mattis tellus. Mauris tellus massa, vulputate sit amet mauris et, varius dapibus ipsum. Donec porta lobortis laoreet. Quisque nec diam ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam viverra faucibus nunc, et rutrum mi viverra at. Proin et ipsum velit.

Integer vel ornare lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris a luctus ex. Phasellus congue eros nec libero consectetur, feugiat molestie sem imperdiet. Sed tellus ligula, condimentum a lectus at, aliquet ornare erat. Nulla varius facilisis felis eu lobortis. Fusce aliquam sit amet justo eget sodales. Sed tortor diam, rhoncus eu consequat eget, convallis id ex. Nulla ac erat sit amet eros ullamcorper cursus sit amet et sapien. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut finibus sapien vitae malesuada malesuada. Integer malesuada sed tellus at tempus. Duis porttitor, diam ullamcorper tempus imperdiet, magna odio mattis lacus, sit amet fringilla tortor nisi eu dui. Vivamus risus tortor, mattis non ultricies nec, congue eu purus. Fusce egestas fringilla diam, sed accumsan metus porttitor nec. Morbi ullamcorper sollicitudin auctor.

In ut risus tellus. Ut fringilla facilisis ex, ut porttitor quam iaculis sed. Aenean ac finibus mauris. Etiam id dapibus quam. Etiam at turpis placerat, dictum justo et, lobortis nisl. Sed lorem urna, aliquet venenatis urna sit amet, sagittis finibus mauris. Nulla consectetur nibh eu lacus mollis ullamcorper. Sed fringilla non neque eu semper. Mauris sagittis mi eget ipsum imperdiet dictum eu quis lacus. In sit amet nisl eget neque volutpat iaculis. Quisque auctor ipsum eu augue vehicula, et pharetra ipsum scelerisque. Quisque orci quam, auctor ac condimentum consequat, pulvinar quis ipsum. Aenean blandit luctus posuere.

Quisque et molestie velit, id vestibulum erat. Aliquam accumsan id lacus non pharetra. Donec rutrum sagittis efficitur. Sed vel mauris ullamcorper, facilisis metus nec, ornare odio. Cras posuere dapibus risus vel convallis. Phasellus facilisis felis eu blandit feugiat. Praesent semper lacinia enim posuere efficitur. Donec augue leo, lacinia at fringilla id, finibus vel magna. Etiam semper felis a dignissim finibus. Nulla lacinia nunc augue, non condimentum odio venenatis vitae. Praesent eu erat id nibh vehicula dapibus vel sit amet justo. Fusce tempor, mauris id eleifend imperdiet, nisl odio lobortis est, vel mattis felis mauris nec lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Suspendisse tempor eros a ornare placerat. Etiam accumsan eu mi ultrices efficitur. Pellentesque at risus suscipit, venenatis nulla eget, sollicitudin magna. Cras nec massa vel est pharetra placerat. Fusce porta dui eget lacus laoreet tincidunt. Aliquam sed enim et est scelerisque dictum. Fusce in auctor justo. Vestibulum tincidunt nisi ut accumsan viverra. Aliquam erat volutpat. Maecenas pellentesque dignissim interdum. Sed vel molestie mauris, sed volutpat est. Mauris egestas purus non euismod dapibus. Aliquam dictum tincidunt metus quis egestas. Praesent euismod enim vel massa placerat, nec imperdiet dui gravida. Donec a libero et elit finibus posuere tincidunt id leo.

Sed ac urna id tellus interdum euismod et vel mi. Praesent eu consectetur leo, sit amet convallis eros. Integer non viverra massa, at porta libero. Vivamus a ante pulvinar ligula scelerisque placerat. Maecenas lobortis et nibh non gravida. Nulla ornare augue elit, elementum convallis dolor tempor nec. Aenean quis quam nec nibh tincidunt iaculis.

Phasellus elementum orci felis, eu semper sem tincidunt et. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam eget sem quis arcu mattis volutpat. Quisque vestibulum, nibh et ullamcorper dapibus, elit massa sollicitudin ex, at varius turpis diam non risus. Vivamus accumsan leo molestie euismod egestas. Phasellus aliquet ultricies nulla, et lobortis nisl dignissim non. Aliquam vitae sagittis metus, nec feugiat est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur consectetur efficitur quam, et consequat elit interdum a. Quisque molestie fringilla odio non convallis. Duis quis sapien molestie, tincidunt ante nec, vulputate lacus. Donec est nulla, congue a nulla sit amet, faucibus aliquet urna. Fusce at tristique mi. Maecenas elit augue, bibendum et massa sit amet, euismod porttitor justo. Nulla commodo imperdiet massa eget convallis.

In tempus hendrerit suscipit. Integer aliquet, orci ac bibendum viverra, sapien lorem elementum urna, a maximus leo tellus ac odio. Nulla non arcu vitae libero viverra dictum. Vestibulum eget molestie erat. Phasellus condimentum sed velit vel porttitor. Nam vel cursus enim, id sodales tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc vitae erat magna. Vestibulum venenatis mi libero, vitae aliquet erat bibendum sit amet. Donec mi nunc, condimentum vitae arcu id, posuere consectetur ex. Donec molestie fermentum metus, non consectetur nisi sagittis sit amet. Nam id neque vel risus ullamcorper laoreet.

Sed eu scelerisque nisl, quis imperdiet sapien. Ut maximus aliquet nisi, ut placerat sem tincidunt at. Aenean efficitur diam consequat orci auctor, ut dictum odio posuere. Mauris quis egestas neque. Duis interdum erat sed tincidunt dictum. Praesent tempus eget elit sed maximus. Duis ac maximus eros. Praesent in eros id dui egestas suscipit. Sed mattis leo a euismod ullamcorper.

Cras diam mi, ultrices in vehicula pulvinar, ornare vitae elit. Integer in enim ligula. Phasellus pharetra suscipit sem, nec elementum orci ullamcorper at. Nulla quis congue mi. Duis in sem ut ipsum elementum consequat eu eu odio. Cras sit amet leo eget est laoreet lacinia eu nec lorem. Proin commodo sollicitudin neque ac iaculis. Morbi consectetur massa sodales erat scelerisque, eu pharetra lectus volutpat. Vestibulum faucibus sed enim ut bibendum. Praesent ornare vulputate auctor. Curabitur porta ullamcorper dapibus. Pellentesque ut metus sit amet purus fermentum fermentum ac vitae libero. Praesent sagittis mollis ante sit amet commodo. Donec vel porta tellus.</p>
  </>
}

export default App
